### ISSUE TITLE
Too many storage space overhead when loading dataset

### ISSUE THREAD

**Issue by Ch3nYe** [Qihoo360/360-LLaMA-Factory#9]
### Reminder

- [x] I have read the README and searched the existing issues.

### System Info

It's a great work, but I have some problem here:

When I load a 270k dataset (2.7GB file) using 32k context truncate, I enable the `sequence_parallel_size=4`.
Finally, the 360-llama-factory takes 1.5TB storage memory, what happened here, and can we improve the storage usage?
It occurred in a `datasets.Dataset.map` operation.

Map:   0%|▌            | 1000/277146 [00:12<57:44, 79.71 examples/s]

Also, the speed is too slow (40-70 ex/s).

The following is the yaml file used to launch training.

### Reproduction

```yaml
### cmd: CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 llamafactory-cli train qwen_full_sft_ds3.yaml

### model
model_name_or_path: LLMs/Qwen2.5-Coder-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: ds_z3_config.json

### dataset
dataset_dir: dataset
dataset: test-sft
template: qwen
default_system: "You are a helpful assistant."
cutoff_len: 32768
# max_samples: 2800 # for debug
preprocessing_num_workers: 16
overwrite_cache: false
tokenized_path: dataset/dataset-for-beta/train-sft-tokenized
# disable_shuffling: true

### output
output_dir: models/test-sft
save_strategy: steps
save_steps: 250
plot_loss: true
overwrite_output_dir: true


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
num_train_epochs: 2.0
learning_rate: 8.0e-6
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs: {'min_lr': 8.0e-7}
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
# use_unsloth_gc: true
# enable_liger_kernel: true
sequence_parallel_size: 4

### eval
do_eval: false


### speed up
flash_attn: fa2

### logging
logging_steps: 5
report_to: wandb
```
